# Generated by Django 5.0.4 on 2024-04-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='tmp', max_length=50),
            preserve_default=False,
        ),
    ]
