# Generated by Django 5.0.4 on 2024-04-18 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_alter_user_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPin',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_api.user')),
                ('pin', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
    ]
